[package]
name = "restaking"
version = "1.0.0"
authors = []

[addresses]
aptos_framework = "0x1"
deployer = "0x1efa8b2fc5b2c5d9124868881b8dd6052a7d43e64cf2561c57946e1244864658"
restaking = "0x9043645412966f87e3521c1cb796ad8ea1a5ecaf0f488da8d2c96b664da9dd00"

[dev-addresses]
# deployer = "0xcafe"
restaking = "0xc3bb8488ab1a5815a9d543d7e41b0e0df46a7396f89b22821f07a4362f75ddc5"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
